services:
  bff:
    build: ./bff
    ports:
      - "3000:3000"
    volumes:
      - ./bff:/app
      - /app/node_modules
    environment:
      - DRAWER_URL=http://localhost:3001
      - VIDEOS_URL=http://localhost:3002
      - YT_API_KEY=
      - YT_API_URL=https://www.googleapis.com/youtube/v3/search
      - YT_API_REFERER=http://localhost:3000
  mf_drawer:
    build: ./mf_drawer
    ports:
      - "3001:3001"
    volumes:
      - ./mf_drawer:/app
  mf_videos:
    build: ./mf_videos
    ports:
      - "3002:3002"
    volumes:
      - ./mf_videos:/app